apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  storageClassName: standard
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: elasticsearch
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  volumeName: elasticsearch
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
